#!/usr/bin/env python3
"""Generate Foundation localization resources from the reviewed, credential-free catalog."""
import argparse,json,re
from pathlib import Path
root=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser()
parser.add_argument('--check',action='store_true')
parser.add_argument('--bootstrap',action='store_true',help=argparse.SUPPRESS)
args=parser.parse_args()
locales=['en','zh-Hans','zh-Hant','ja','ko','es','pt-BR','fr','de','ar','hi','id']
catalog=json.loads((root/'localization/catalog.json').read_text())
errors=[]
def placeholders(value): return sorted(re.findall(r'%(?:[1-9]\d*\$)?(?:ld|@)',value))
for scope,folder in [('app','VaultReader/Resources/Localization'),('core','packages/VaultCore/Sources/VaultCore/Resources')]:
    for locale in locales:
        output=['/* Generated by scripts/build-localizations.py. Edit localization/catalog.json. */']
        for key,entry in sorted(catalog.items()):
            if entry['scope']!=scope: continue
            value=entry['translations'].get(locale)
            if value is None:
                if args.bootstrap: continue
                errors.append(f'{locale}: missing {key}'); continue
            if placeholders(value)!=placeholders(key): errors.append(f'{locale}: placeholder mismatch for {key}')
            output.append(json.dumps(key,ensure_ascii=False)+' = '+json.dumps(value,ensure_ascii=False)+';')
        content='\n'.join(output)+'\n'; path=root/folder/(locale+'.lproj')/'Localizable.strings'
        if args.check:
            if not path.exists() or path.read_text()!=content: errors.append(f'Stale generated resource: {path.relative_to(root)}')
        else:
            path.parent.mkdir(parents=True,exist_ok=True); path.write_text(content)
if errors: raise SystemExit('\n'.join(errors))
print(f'Localization resources {"verified" if args.check else "generated"}: {len(catalog)} keys, {len(locales)} languages.')
